### ISSUE TITLE
Implement dark and night theme

### ISSUE THREAD

**Issue by Abusayid693** [Abusayid693/Hackathon-website-template#20]
- Make a component that wraps entire application(use context API)
- organise all colours in global.css with class name
- use css property to toggle theme

Eg : 
```css
.black {
  color: black;
}

[data-theme = "dark"]  {
 .black {
   color: white;
 }
}
```
